main	: 
	g++ -std=c++11 -o main main.cpp board.cpp makhluk.cpp manager.cpp point.cpp viewer.cpp -pthread	
clean	:
	rm main
	g++ -std=c++11 -o main main.cpp board.cpp makhluk.cpp manager.cpp point.cpp viewer.cpp -pthread	

